# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
basketball = Category.create(name: 'Basketball')
pingpong = Category.create(name: 'Pingpong')
tennis = Category.create(name: 'Tennis')
user1 = User.create(username: "Steve", password_digest: "12345")
goods1 = Item.create(name: 'Adidas B72768 CRAZY BOUNCE',price:50, category: basketball,user:user1,img_url: "https://www.burghardtsportinggoods.com/Products/ProductImages/88913855171F.jpg")
goods2 = Item.create(name:'Baden Sports Inc B6B Basketball Bag',price: 30,category: basketball,user:user1, img_url:'https://www.burghardtsportinggoods.com/Products/ProductImages/02030216754F.png')
goods3 = Item.create(name:'Baden Sports Inc BR400 Rubber Basketball',price:20,category: basketball,user:user1, img_url:'https://www.burghardtsportinggoods.com/Products/ProductImages/05212527400F.jpg')
goods4 = Item.create(name:'Bison BA51H Net Anti Whip',price:10,category: basketball,user:user1, img_url:'https://www.burghardtsportinggoods.com/Products/ProductImages/00558670788F.jpg')
goods5 = Item.create(name:'Champro Sports Equip BR16 Ball Rack w/Casters',price:90,category: basketball,user:user1, img_url:'https://www.burghardtsportinggoods.com/Products/ProductImages/00720991841F.jpg')
goods6 = Item.create(name:'Escalade Sports T1364 Performance 4-Player Set',price:30,category: pingpong,user:user1, img_url:'https://www.burghardtsportinggoods.com/Products/ProductImages/75480612565F.jpg')
goods7 = Item.create(name:'Escalade Sports T1413 1-Star Orange (6 Pack)',price:20, category: pingpong,user:user1, img_url:'https://www.burghardtsportinggoods.com/Products/ProductImages/75480612554F.jpg')
goods8 = Item.create(name:'Escalade Sports T1575 Racket Cover',price:10, category: pingpong,user:user1, img_url:'https://www.burghardtsportinggoods.com/Products/ProductImages/75480612563F.jpg')
goods9 = Item.create(name:'Escalade Sports T8612 Stiga Legacy Table',price:400,category: pingpong,user:user1, img_url:'https://www.burghardtsportinggoods.com/Products/ProductImages/00566532978F.jpg')
goods10 = Item.create(name:'Escalade Sports T1270 Supreme Racket',price:30,category: pingpong,user:user1, img_url:'https://www.burghardtsportinggoods.com/Products/ProductImages/75480612547F.jpg')
goods11 = Item.create(name:'Mueller Sports Medicine 74111 Ladies Life Care Contour Elbow Support',price:20,category: tennis,user:user1,img_url:'https://www.burghardtsportinggoods.com/Products/ProductImages/07467674111F.JPG')
goods12 = Item.create(name:'Glover Easy Scorebooks TN-504 Tennis Scorebook',price:5,category: tennis,user:user1,img_url:'https://www.burghardtsportinggoods.com/Products/ProductImages/1833850002202F.jpg')
goods13 = Item.create(name:'Wilson Racket Sport WRT21030U Junior US Open 25" Tennis Racquet',price:60,category: tennis,user:user1,img_url:'https://www.burghardtsportinggoods.com/Products/ProductImages/88776828745F.jpg')
goods14 = Item.create(name:'Wilson Racket Sport Wrz820495 Tennis Racquet Backpack',price:40,category: tennis,user:user1,img_url:'https://www.burghardtsportinggoods.com/Products/ProductImages/88776816286F.jpg')
goods15 = Item.create(name:'United Sports Brands MD489R Level 2 Elbow Strap with Pads',price:10,category: tennis,user:user1,img_url:'https://www.burghardtsportinggoods.com/Products/ProductImages/02936948903F.jpg')
goods16 = Item.create(name:'Tandem 3-Digit Score Flipper',price:30,category: basketball,user:user1,img_url:'https://dks.scene7.com/is/image/GolfGalaxy/16TANUSCRFLPPR3DGVLL?wid=500&fmt=jpg')
goods17 = Item.create(name:'Goalrilla Basketball Hoop Yard Guard',price:120,category: basketball,user:user1,img_url:'https://dks.scene7.com/is/image/GolfGalaxy/16GLRUGLRLLYRDGRDBKA?wid=500&fmt=jpg')
goods18 = Item.create(name:'Goalrilla LED Basketball Hoop Light',price:109,category: basketball,user:user1,img_url:'https://dks.scene7.com/is/image/GolfGalaxy/18GLRUGLRLLLDHPLGBKA?wid=500&fmt=jpg')
goods19 = Item.create(name:'Nike Kyrie 4 TB Basketball Shoes',price:92,category: basketball,user:user1,img_url:'https://dks.scene7.com/is/image/dkscdn/18NIKMKYR4TBBLKWHMNKA_Black_White?wid=425')
goods20 = Item.create(name:'Lifetime Heavy Duty 120-Gram Basketball Net',price:10,category: basketball,user:user1,img_url:'https://dks.scene7.com/is/image/GolfGalaxy/16LIFU120GRM21NTXBKA?wid=500&fmt=jpg')
goods21 = Item.create(name:'Lobster Sports elite freedom Tennis Ball Machine',price:510,category: tennis,user:user1,img_url:'https://dks.scene7.com/is/image/GolfGalaxy/16LSPULTFRDMPRTBLTNN?wid=500&fmt=jpg')
goods22 = Item.create(name:'Nike Court Lite Tennis Shoes',price:103,category: tennis,user:user1,img_url:'https://dks.scene7.com/is/image/GolfGalaxy/16NIKMCRTLTWHTBLKTNN_Grey_Black_Red?wid=500&fmt=jpg')
goods23 = Item.create(name:'Tourna Classic Ballport 70',price:70,category: tennis,user:user1,img_url:'https://dks.scene7.com/is/image/GolfGalaxy/16TOUUBLLPRTCLSSCTNN?wid=500&fmt=jpg')
goods24 = Item.create(name:"Nike Court Men's Lite Tennis Shoes",price:83,category: tennis,user:user1,img_url:'https://dks.scene7.com/is/image/dkscdn/16NIKWPRTNKXXXXXXTPSX_Igloo?wid=425')
goods25 = Item.create(name:"Nike Women's Pure Tennis Tank Top",price:30,category: tennis,user:user1,img_url:'https://m.media-amazon.com/images/I/81I0qsjuPCL._SX480_.jpg')
goods26 = Item.create(name:"JOOLA Tour Table Tennis Case",price:50,category: pingpong,user:user1,img_url:'https://jetimages.jetcdn.net/md5/49ac6d166fc6c7a8eec9a6b0f53709df')
goods27 = Item.create(name:"JOOLA Table Tennis Practice Net",price:63,category: pingpong,user:user1,img_url:'https://dks.scene7.com/is/image/GolfGalaxy/16JOOUCMPCTCRBNFBSTG?wid=500&fmt=jpg')
goods28 = Item.create(name:"JOOLA Avanti Table Tennis Net",price:45,category: pingpong,user:user1,img_url:'https://dks.scene7.com/is/image/GolfGalaxy/16JOOUVNTNTXXXXXXSTG?wid=500&fmt=jpg')
goods29 = Item.create(name:"JOOLA Table Tennis Table Cover",price:33,category: pingpong,user:user1,img_url:'https://dks.scene7.com/is/image/GolfGalaxy/16JOOUTBLCVRXXXXXSTG?wid=500&fmt=jpg')
goods30 = Item.create(name:"iPong Expert Table Tennis Robot",price:132,category: pingpong,user:user1,img_url:'https://dks.scene7.com/is/image/GolfGalaxy/17JOOUPNGXPRTXXXXSTG?wid=500&fmt=jpg')
goods31 = Item.create(name:"iPong Topspin Table Tennis Trainer Robot",price:102,category: pingpong,user:user1,img_url:'https://dks.scene7.com/is/image/GolfGalaxy/16JOOUPNGTPSPNXXXSTG?wid=500&fmt=jpg')
goods32 = Item.create(name:"Butterfly Addoy 3000 Table Tennis Racket",price:42,category: pingpong,user:user1,img_url:'https://dks.scene7.com/is/image/GolfGalaxy/16BUTUDDY3000RCKTSTG?wid=500&fmt=jpg')
goods33 = Item.create(name:"JOOLA 500 mL Table Tennis Table Cleaner",price:22,category: pingpong,user:user1,img_url:'https://dks.scene7.com/is/image/GolfGalaxy/17SSQUTBLCLNR500MSTG?wid=500&fmt=jpg')
goods34 = Item.create(name:"iPong Practice Table Tennis Targets",price:12,category: pingpong,user:user1,img_url:'https://dks.scene7.com/is/image/GolfGalaxy/16JOOUPNGTRGTSXXXSTG?wid=500&fmt=jpg')
goods35 = Item.create(name:"Prince Classic Table Tennis Net & Post Set",price:32,category: pingpong,user:user1,img_url:'https://dks.scene7.com/is/image/GolfGalaxy/18PRCUPRNCCLSSCNTSTG?wid=500&fmt=jpg')
goods36 = Item.create(name:"Nike Women's Feather Light Adjustable Hat",price:23,category: tennis,user:user1,img_url:'https://dks.scene7.com/is/image/GolfGalaxy/16NIKWWSFTHRLGHTCCPS_Igloo?wid=500&fmt=jpg')
goods37 = Item.create(name:"Penn Championship Regular Duty Tennis Balls - 6 Can Pack",price:43,category: tennis,user:user1,img_url:'https://dks.scene7.com/is/image/GolfGalaxy/16PENURGLRDTY6PCKTNN-1?wid=500&fmt=jpg')
goods38 = Item.create(name:"Nike Women's Printed Pure Tennis Skirt",price:38,category: tennis,user:user1,img_url:'https://dks.scene7.com/is/image/GolfGalaxy/18NIKWPRNTDPRSKRTBTT_Team_Red_White?wid=500&fmt=jpg')
goods39 = Item.create(name:"Babolat Syntec Pro Replacement Grip",price:13,category: tennis,user:user1,img_url:'https://dks.scene7.com/is/image/GolfGalaxy/16BABUSYNTCPRXXXXTNN_White?wid=500&fmt=jpg')
goods40 = Item.create(name:"Babolat RH Classic Club Racquet Bag x 6",price:45,category: tennis,user:user1,img_url:'https://dks.scene7.com/is/image/GolfGalaxy/18BABURHCLSSCCLBXTNN?wid=500&fmt=jpg')
goods41 = Item.create(name:'McDavid HEX Extended Leg Sleeves - Pair',price:20,category: basketball,user:user1, img_url:'https://dks.scene7.com/is/image/GolfGalaxy/16MCVAMCDVDHXLGSLBKA_MGrid?wid=500&fmt=jpg')
goods42 = Item.create(name:'McDavid Adult TEFLX 3/4 Length Tights',price:22,category: basketball,user:user1, img_url:'https://dks.scene7.com/is/image/GolfGalaxy/17MCVATFLX34TGHTXBKA_White?wid=500&fmt=jpg')
goods43 = Item.create(name:'Nike Hoops Elite Pro Basketball Backpack',price:80,category: basketball,user:user1, img_url:'https://dks.scene7.com/is/image/GolfGalaxy/18NIKUHPSLTPRXXXXTRV_Black_Black_Mtlc?wid=500&fmt=jpg')
goods44 = Item.create(name:'Nike LeBron 15 Low Basketball Shoes',price:60,category: basketball,user:user1, img_url:'https://dks.scene7.com/is/image/GolfGalaxy/18NIKMLBRN15LWBLGMNK_Signal_Blue?wid=500&fmt=jpg')
goods45 = Item.create(name:'Nike True Grip Official Basketball',price:30,category: basketball,user:user1, img_url:'https://dks.scene7.com/is/image/GolfGalaxy/17NIKUNKTRGRP2017BKBA?wid=500&fmt=jpg')
goods46 = Item.create(name:'Lifetime Universal Backboard Mounting Kit',price:300,category: basketball,user:user1, img_url:'https://dks.scene7.com/is/image/GolfGalaxy/16LIFUNVRSLMNTNGKBKA?wid=500&fmt=jpg')
goods47 = Item.create(name:'Nike Essential Ball Pump',price:10,category: basketball,user:user1, img_url:'https://dks.scene7.com/is/image/GolfGalaxy/18NIKUSSNTLBLLPMPGAA_Black_White?wid=500&fmt=jpg')
goods48 = Item.create(name:"Under Armour Boys' SC30 Essentials Sleeveless Shirt",price:30,category: basketball,user:user1, img_url:'https://dks.scene7.com/is/image/GolfGalaxy/16UARBSC30SSNTLSTAPT_Red_White?wid=500&fmt=jpg')
goods49 = Item.create(name:"Jordan Men's Ultra Fly 2 Low Basketball Shoes",price:100,category: basketball,user:user1, img_url:'https://dks.scene7.com/is/image/GolfGalaxy/17JDNMRJRDNLTRFLYJRD_Black_Gold?wid=500&fmt=jpg')
goods50 = Item.create(name:"Champion 48 Ball Double Wide Ball Rack",price:30,category: basketball,user:user1, img_url:'https://dks.scene7.com/is/image/GolfGalaxy/16CPSU48BLLDBLWDBBKA?wid=500&fmt=jpg')
goods51 = Item.create(name:"Prince Women's Match T-Shirt",price:25,category: tennis,user:user1,img_url:'https://dks.scene7.com/is/image/GolfGalaxy/18PRCWMTCHSSTXXXXTPS_White?wid=500&fmt=jpg')
goods52 = Item.create(name:"adidas Men's Athletic No Show Socks 6 Pack",price:20,category: tennis,user:user1,img_url:'https://dks.scene7.com/is/image/GolfGalaxy/16ADIM6PKNSHW1013APA_Black_Metallic_Silver?wid=500&fmt=jpg')
goods53 = Item.create(name:"Tourna Fill-n-Drill Tennis Trainer",price:60,category: tennis,user:user1,img_url:'https://dks.scene7.com/is/image/GolfGalaxy/16TOUUFLLNDRLLTNNTNN?wid=500&fmt=jpg')
goods54 = Item.create(name:"Head Core Pro 3 Pack Tennis Bag",price:73,category: tennis,user:user1,img_url:'https://dks.scene7.com/is/image/GolfGalaxy/16HEDUCRPR3PKBG20TNN_Black_White?wid=500&fmt=jpg')
goods55 = Item.create(name:"Viking O-Zone Pro Platform Tennis Paddle",price:103,category: tennis,user:user1,img_url:'https://dks.scene7.com/is/image/GolfGalaxy/16VIKUZNPRXXXXXXXPLT?wid=500&fmt=jpg')
goods56 = Item.create(name:"Franklin 2 Player Table Tennis Paddle and Ball Set",price:12,category: pingpong,user:user1,img_url:'https://dks.scene7.com/is/image/GolfGalaxy/16FRAU2PLYRPDDLBLSTG?wid=500&fmt=jpg')
goods57 = Item.create(name:"Butterfly 201 FL Table Tennis Racket",price:32,category: pingpong,user:user1,img_url:'https://dks.scene7.com/is/image/GolfGalaxy/16BUTUBTY201FLRCKSTG?wid=500&fmt=jpg')
goods58 = Item.create(name:"Franklin 144-Pack 40mm Table Tennis Balls",price:40,category: pingpong,user:user1,img_url:'https://dks.scene7.com/is/image/GolfGalaxy/17FRAU0MM1STRRNGNSTG?wid=500&fmt=jpg')
goods59 = Item.create(name:"Pong PRO Table Tennis Training Robot with Oscillation and Remote",price:182,category: pingpong,user:user1,img_url:'https://dks.scene7.com/is/image/GolfGalaxy/16JOOUPNGPRXXXXXXSTG?wid=500&fmt=jpg')
goods60 = Item.create(name:"Butterfly Outdoor Playback Rollaway Table Tennis Table",price:499,category: pingpong,user:user1,img_url:'https://dks.scene7.com/is/image/GolfGalaxy/16BUTUTDRPLYBCKRLSTG_Blue?wid=500&fmt=jpg')
